#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Exam
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="onlineExam")]
	public partial class mainDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKelas(Kelas instance);
    partial void UpdateKelas(Kelas instance);
    partial void DeleteKelas(Kelas instance);
    partial void InsertMapel(Mapel instance);
    partial void UpdateMapel(Mapel instance);
    partial void DeleteMapel(Mapel instance);
    partial void InsertSiswa(Siswa instance);
    partial void UpdateSiswa(Siswa instance);
    partial void DeleteSiswa(Siswa instance);
    partial void InsertGuru(Guru instance);
    partial void UpdateGuru(Guru instance);
    partial void DeleteGuru(Guru instance);
    partial void InsertUjian(Ujian instance);
    partial void UpdateUjian(Ujian instance);
    partial void DeleteUjian(Ujian instance);
    partial void InsertdetailKela(detailKela instance);
    partial void UpdatedetailKela(detailKela instance);
    partial void DeletedetailKela(detailKela instance);
    partial void InsertHeaderSoal(HeaderSoal instance);
    partial void UpdateHeaderSoal(HeaderSoal instance);
    partial void DeleteHeaderSoal(HeaderSoal instance);
    partial void InsertDetailSoal(DetailSoal instance);
    partial void UpdateDetailSoal(DetailSoal instance);
    partial void DeleteDetailSoal(DetailSoal instance);
    #endregion
		
		public mainDataDataContext() : 
				base(global::Online_Exam.Properties.Settings.Default.onlineExamConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public mainDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public mainDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public mainDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public mainDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AksesMapel> AksesMapels
		{
			get
			{
				return this.GetTable<AksesMapel>();
			}
		}
		
		public System.Data.Linq.Table<Kelas> Kelas
		{
			get
			{
				return this.GetTable<Kelas>();
			}
		}
		
		public System.Data.Linq.Table<Mapel> Mapels
		{
			get
			{
				return this.GetTable<Mapel>();
			}
		}
		
		public System.Data.Linq.Table<Siswa> Siswas
		{
			get
			{
				return this.GetTable<Siswa>();
			}
		}
		
		public System.Data.Linq.Table<AksesKelas> AksesKelas
		{
			get
			{
				return this.GetTable<AksesKelas>();
			}
		}
		
		public System.Data.Linq.Table<Guru> Gurus
		{
			get
			{
				return this.GetTable<Guru>();
			}
		}
		
		public System.Data.Linq.Table<Ujian> Ujians
		{
			get
			{
				return this.GetTable<Ujian>();
			}
		}
		
		public System.Data.Linq.Table<detailKela> detailKelas
		{
			get
			{
				return this.GetTable<detailKela>();
			}
		}
		
		public System.Data.Linq.Table<HeaderSoal> HeaderSoals
		{
			get
			{
				return this.GetTable<HeaderSoal>();
			}
		}
		
		public System.Data.Linq.Table<DetailSoal> DetailSoals
		{
			get
			{
				return this.GetTable<DetailSoal>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AksesMapel")]
	public partial class AksesMapel
	{
		
		private System.Nullable<int> _idMapel;
		
		private string _idGuru;
		
		public AksesMapel()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMapel", DbType="Int")]
		public System.Nullable<int> idMapel
		{
			get
			{
				return this._idMapel;
			}
			set
			{
				if ((this._idMapel != value))
				{
					this._idMapel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idGuru", DbType="VarChar(10)")]
		public string idGuru
		{
			get
			{
				return this._idGuru;
			}
			set
			{
				if ((this._idGuru != value))
				{
					this._idGuru = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kelas")]
	public partial class Kelas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idKelas;
		
		private string _namaKelas;
		
		private EntitySet<HeaderSoal> _HeaderSoals;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidKelasChanging(int value);
    partial void OnidKelasChanged();
    partial void OnnamaKelasChanging(string value);
    partial void OnnamaKelasChanged();
    #endregion
		
		public Kelas()
		{
			this._HeaderSoals = new EntitySet<HeaderSoal>(new Action<HeaderSoal>(this.attach_HeaderSoals), new Action<HeaderSoal>(this.detach_HeaderSoals));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idKelas", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idKelas
		{
			get
			{
				return this._idKelas;
			}
			set
			{
				if ((this._idKelas != value))
				{
					this.OnidKelasChanging(value);
					this.SendPropertyChanging();
					this._idKelas = value;
					this.SendPropertyChanged("idKelas");
					this.OnidKelasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_namaKelas", DbType="VarChar(3)")]
		public string namaKelas
		{
			get
			{
				return this._namaKelas;
			}
			set
			{
				if ((this._namaKelas != value))
				{
					this.OnnamaKelasChanging(value);
					this.SendPropertyChanging();
					this._namaKelas = value;
					this.SendPropertyChanged("namaKelas");
					this.OnnamaKelasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kelas_HeaderSoal", Storage="_HeaderSoals", ThisKey="idKelas", OtherKey="idKelas")]
		public EntitySet<HeaderSoal> HeaderSoals
		{
			get
			{
				return this._HeaderSoals;
			}
			set
			{
				this._HeaderSoals.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HeaderSoals(HeaderSoal entity)
		{
			this.SendPropertyChanging();
			entity.Kelas = this;
		}
		
		private void detach_HeaderSoals(HeaderSoal entity)
		{
			this.SendPropertyChanging();
			entity.Kelas = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Mapel")]
	public partial class Mapel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idMapel;
		
		private string _namaMapel;
		
		private System.Nullable<int> _Kkm;
		
		private EntitySet<HeaderSoal> _HeaderSoals;
		
		private EntitySet<DetailSoal> _DetailSoals;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidMapelChanging(int value);
    partial void OnidMapelChanged();
    partial void OnnamaMapelChanging(string value);
    partial void OnnamaMapelChanged();
    partial void OnKkmChanging(System.Nullable<int> value);
    partial void OnKkmChanged();
    #endregion
		
		public Mapel()
		{
			this._HeaderSoals = new EntitySet<HeaderSoal>(new Action<HeaderSoal>(this.attach_HeaderSoals), new Action<HeaderSoal>(this.detach_HeaderSoals));
			this._DetailSoals = new EntitySet<DetailSoal>(new Action<DetailSoal>(this.attach_DetailSoals), new Action<DetailSoal>(this.detach_DetailSoals));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMapel", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idMapel
		{
			get
			{
				return this._idMapel;
			}
			set
			{
				if ((this._idMapel != value))
				{
					this.OnidMapelChanging(value);
					this.SendPropertyChanging();
					this._idMapel = value;
					this.SendPropertyChanged("idMapel");
					this.OnidMapelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_namaMapel", DbType="VarChar(100)")]
		public string namaMapel
		{
			get
			{
				return this._namaMapel;
			}
			set
			{
				if ((this._namaMapel != value))
				{
					this.OnnamaMapelChanging(value);
					this.SendPropertyChanging();
					this._namaMapel = value;
					this.SendPropertyChanged("namaMapel");
					this.OnnamaMapelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kkm", DbType="Int")]
		public System.Nullable<int> Kkm
		{
			get
			{
				return this._Kkm;
			}
			set
			{
				if ((this._Kkm != value))
				{
					this.OnKkmChanging(value);
					this.SendPropertyChanging();
					this._Kkm = value;
					this.SendPropertyChanged("Kkm");
					this.OnKkmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mapel_HeaderSoal", Storage="_HeaderSoals", ThisKey="idMapel", OtherKey="idMapel")]
		public EntitySet<HeaderSoal> HeaderSoals
		{
			get
			{
				return this._HeaderSoals;
			}
			set
			{
				this._HeaderSoals.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mapel_DetailSoal", Storage="_DetailSoals", ThisKey="idMapel", OtherKey="idMapel")]
		public EntitySet<DetailSoal> DetailSoals
		{
			get
			{
				return this._DetailSoals;
			}
			set
			{
				this._DetailSoals.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HeaderSoals(HeaderSoal entity)
		{
			this.SendPropertyChanging();
			entity.Mapel = this;
		}
		
		private void detach_HeaderSoals(HeaderSoal entity)
		{
			this.SendPropertyChanging();
			entity.Mapel = null;
		}
		
		private void attach_DetailSoals(DetailSoal entity)
		{
			this.SendPropertyChanging();
			entity.Mapel = this;
		}
		
		private void detach_DetailSoals(DetailSoal entity)
		{
			this.SendPropertyChanging();
			entity.Mapel = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Siswa")]
	public partial class Siswa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idSiswa;
		
		private string _fullName;
		
		private string _kelas;
		
		private string _password;
		
		private string _role;
		
		private System.Nullable<int> _idDetailKelas;
		
		private EntitySet<Ujian> _Ujians;
		
		private EntityRef<detailKela> _detailKela;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidSiswaChanging(string value);
    partial void OnidSiswaChanged();
    partial void OnfullNameChanging(string value);
    partial void OnfullNameChanged();
    partial void OnkelasChanging(string value);
    partial void OnkelasChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnroleChanging(string value);
    partial void OnroleChanged();
    partial void OnidDetailKelasChanging(System.Nullable<int> value);
    partial void OnidDetailKelasChanged();
    #endregion
		
		public Siswa()
		{
			this._Ujians = new EntitySet<Ujian>(new Action<Ujian>(this.attach_Ujians), new Action<Ujian>(this.detach_Ujians));
			this._detailKela = default(EntityRef<detailKela>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSiswa", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idSiswa
		{
			get
			{
				return this._idSiswa;
			}
			set
			{
				if ((this._idSiswa != value))
				{
					this.OnidSiswaChanging(value);
					this.SendPropertyChanging();
					this._idSiswa = value;
					this.SendPropertyChanged("idSiswa");
					this.OnidSiswaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullName", DbType="VarChar(100)")]
		public string fullName
		{
			get
			{
				return this._fullName;
			}
			set
			{
				if ((this._fullName != value))
				{
					this.OnfullNameChanging(value);
					this.SendPropertyChanging();
					this._fullName = value;
					this.SendPropertyChanged("fullName");
					this.OnfullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kelas", DbType="VarChar(3)")]
		public string kelas
		{
			get
			{
				return this._kelas;
			}
			set
			{
				if ((this._kelas != value))
				{
					this.OnkelasChanging(value);
					this.SendPropertyChanging();
					this._kelas = value;
					this.SendPropertyChanged("kelas");
					this.OnkelasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(100)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="VarChar(100)")]
		public string role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDetailKelas", DbType="Int")]
		public System.Nullable<int> idDetailKelas
		{
			get
			{
				return this._idDetailKelas;
			}
			set
			{
				if ((this._idDetailKelas != value))
				{
					if (this._detailKela.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidDetailKelasChanging(value);
					this.SendPropertyChanging();
					this._idDetailKelas = value;
					this.SendPropertyChanged("idDetailKelas");
					this.OnidDetailKelasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Siswa_Ujian", Storage="_Ujians", ThisKey="idSiswa", OtherKey="idSiswa")]
		public EntitySet<Ujian> Ujians
		{
			get
			{
				return this._Ujians;
			}
			set
			{
				this._Ujians.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="detailKela_Siswa", Storage="_detailKela", ThisKey="idDetailKelas", OtherKey="idDetailKelas", IsForeignKey=true)]
		public detailKela detailKela
		{
			get
			{
				return this._detailKela.Entity;
			}
			set
			{
				detailKela previousValue = this._detailKela.Entity;
				if (((previousValue != value) 
							|| (this._detailKela.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._detailKela.Entity = null;
						previousValue.Siswas.Remove(this);
					}
					this._detailKela.Entity = value;
					if ((value != null))
					{
						value.Siswas.Add(this);
						this._idDetailKelas = value.idDetailKelas;
					}
					else
					{
						this._idDetailKelas = default(Nullable<int>);
					}
					this.SendPropertyChanged("detailKela");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ujians(Ujian entity)
		{
			this.SendPropertyChanging();
			entity.Siswa = this;
		}
		
		private void detach_Ujians(Ujian entity)
		{
			this.SendPropertyChanging();
			entity.Siswa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AksesKelas")]
	public partial class AksesKelas
	{
		
		private System.Nullable<int> _idKelas;
		
		private string _idGuru;
		
		public AksesKelas()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idKelas", DbType="Int")]
		public System.Nullable<int> idKelas
		{
			get
			{
				return this._idKelas;
			}
			set
			{
				if ((this._idKelas != value))
				{
					this._idKelas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idGuru", DbType="VarChar(10)")]
		public string idGuru
		{
			get
			{
				return this._idGuru;
			}
			set
			{
				if ((this._idGuru != value))
				{
					this._idGuru = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Guru")]
	public partial class Guru : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idGuru;
		
		private string _fullName;
		
		private string _password;
		
		private string _role;
		
		private EntitySet<HeaderSoal> _HeaderSoals;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidGuruChanging(string value);
    partial void OnidGuruChanged();
    partial void OnfullNameChanging(string value);
    partial void OnfullNameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnroleChanging(string value);
    partial void OnroleChanged();
    #endregion
		
		public Guru()
		{
			this._HeaderSoals = new EntitySet<HeaderSoal>(new Action<HeaderSoal>(this.attach_HeaderSoals), new Action<HeaderSoal>(this.detach_HeaderSoals));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idGuru", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idGuru
		{
			get
			{
				return this._idGuru;
			}
			set
			{
				if ((this._idGuru != value))
				{
					this.OnidGuruChanging(value);
					this.SendPropertyChanging();
					this._idGuru = value;
					this.SendPropertyChanged("idGuru");
					this.OnidGuruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullName", DbType="VarChar(100)")]
		public string fullName
		{
			get
			{
				return this._fullName;
			}
			set
			{
				if ((this._fullName != value))
				{
					this.OnfullNameChanging(value);
					this.SendPropertyChanging();
					this._fullName = value;
					this.SendPropertyChanged("fullName");
					this.OnfullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(100)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="VarChar(100)")]
		public string role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Guru_HeaderSoal", Storage="_HeaderSoals", ThisKey="idGuru", OtherKey="idGuru")]
		public EntitySet<HeaderSoal> HeaderSoals
		{
			get
			{
				return this._HeaderSoals;
			}
			set
			{
				this._HeaderSoals.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HeaderSoals(HeaderSoal entity)
		{
			this.SendPropertyChanging();
			entity.Guru = this;
		}
		
		private void detach_HeaderSoals(HeaderSoal entity)
		{
			this.SendPropertyChanging();
			entity.Guru = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ujian")]
	public partial class Ujian : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idUjian;
		
		private int _idSoal;
		
		private string _idSiswa;
		
		private System.Nullable<System.DateTime> _tglPengerjaan;
		
		private System.Nullable<int> _nilai;
		
		private EntityRef<Siswa> _Siswa;
		
		private EntityRef<HeaderSoal> _HeaderSoal;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidUjianChanging(int value);
    partial void OnidUjianChanged();
    partial void OnidSoalChanging(int value);
    partial void OnidSoalChanged();
    partial void OnidSiswaChanging(string value);
    partial void OnidSiswaChanged();
    partial void OntglPengerjaanChanging(System.Nullable<System.DateTime> value);
    partial void OntglPengerjaanChanged();
    partial void OnnilaiChanging(System.Nullable<int> value);
    partial void OnnilaiChanged();
    #endregion
		
		public Ujian()
		{
			this._Siswa = default(EntityRef<Siswa>);
			this._HeaderSoal = default(EntityRef<HeaderSoal>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUjian", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idUjian
		{
			get
			{
				return this._idUjian;
			}
			set
			{
				if ((this._idUjian != value))
				{
					this.OnidUjianChanging(value);
					this.SendPropertyChanging();
					this._idUjian = value;
					this.SendPropertyChanged("idUjian");
					this.OnidUjianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSoal", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idSoal
		{
			get
			{
				return this._idSoal;
			}
			set
			{
				if ((this._idSoal != value))
				{
					if (this._HeaderSoal.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidSoalChanging(value);
					this.SendPropertyChanging();
					this._idSoal = value;
					this.SendPropertyChanged("idSoal");
					this.OnidSoalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSiswa", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idSiswa
		{
			get
			{
				return this._idSiswa;
			}
			set
			{
				if ((this._idSiswa != value))
				{
					if (this._Siswa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidSiswaChanging(value);
					this.SendPropertyChanging();
					this._idSiswa = value;
					this.SendPropertyChanged("idSiswa");
					this.OnidSiswaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tglPengerjaan", DbType="DateTime")]
		public System.Nullable<System.DateTime> tglPengerjaan
		{
			get
			{
				return this._tglPengerjaan;
			}
			set
			{
				if ((this._tglPengerjaan != value))
				{
					this.OntglPengerjaanChanging(value);
					this.SendPropertyChanging();
					this._tglPengerjaan = value;
					this.SendPropertyChanged("tglPengerjaan");
					this.OntglPengerjaanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nilai", DbType="Int")]
		public System.Nullable<int> nilai
		{
			get
			{
				return this._nilai;
			}
			set
			{
				if ((this._nilai != value))
				{
					this.OnnilaiChanging(value);
					this.SendPropertyChanging();
					this._nilai = value;
					this.SendPropertyChanged("nilai");
					this.OnnilaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Siswa_Ujian", Storage="_Siswa", ThisKey="idSiswa", OtherKey="idSiswa", IsForeignKey=true)]
		public Siswa Siswa
		{
			get
			{
				return this._Siswa.Entity;
			}
			set
			{
				Siswa previousValue = this._Siswa.Entity;
				if (((previousValue != value) 
							|| (this._Siswa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Siswa.Entity = null;
						previousValue.Ujians.Remove(this);
					}
					this._Siswa.Entity = value;
					if ((value != null))
					{
						value.Ujians.Add(this);
						this._idSiswa = value.idSiswa;
					}
					else
					{
						this._idSiswa = default(string);
					}
					this.SendPropertyChanged("Siswa");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HeaderSoal_Ujian", Storage="_HeaderSoal", ThisKey="idSoal", OtherKey="idSoal", IsForeignKey=true)]
		public HeaderSoal HeaderSoal
		{
			get
			{
				return this._HeaderSoal.Entity;
			}
			set
			{
				HeaderSoal previousValue = this._HeaderSoal.Entity;
				if (((previousValue != value) 
							|| (this._HeaderSoal.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HeaderSoal.Entity = null;
						previousValue.Ujians.Remove(this);
					}
					this._HeaderSoal.Entity = value;
					if ((value != null))
					{
						value.Ujians.Add(this);
						this._idSoal = value.idSoal;
					}
					else
					{
						this._idSoal = default(int);
					}
					this.SendPropertyChanged("HeaderSoal");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.detailKelas")]
	public partial class detailKela : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idDetailKelas;
		
		private System.Nullable<int> _noKelas;
		
		private EntitySet<Siswa> _Siswas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDetailKelasChanging(int value);
    partial void OnidDetailKelasChanged();
    partial void OnnoKelasChanging(System.Nullable<int> value);
    partial void OnnoKelasChanged();
    #endregion
		
		public detailKela()
		{
			this._Siswas = new EntitySet<Siswa>(new Action<Siswa>(this.attach_Siswas), new Action<Siswa>(this.detach_Siswas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDetailKelas", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idDetailKelas
		{
			get
			{
				return this._idDetailKelas;
			}
			set
			{
				if ((this._idDetailKelas != value))
				{
					this.OnidDetailKelasChanging(value);
					this.SendPropertyChanging();
					this._idDetailKelas = value;
					this.SendPropertyChanged("idDetailKelas");
					this.OnidDetailKelasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noKelas", DbType="Int")]
		public System.Nullable<int> noKelas
		{
			get
			{
				return this._noKelas;
			}
			set
			{
				if ((this._noKelas != value))
				{
					this.OnnoKelasChanging(value);
					this.SendPropertyChanging();
					this._noKelas = value;
					this.SendPropertyChanged("noKelas");
					this.OnnoKelasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="detailKela_Siswa", Storage="_Siswas", ThisKey="idDetailKelas", OtherKey="idDetailKelas")]
		public EntitySet<Siswa> Siswas
		{
			get
			{
				return this._Siswas;
			}
			set
			{
				this._Siswas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Siswas(Siswa entity)
		{
			this.SendPropertyChanging();
			entity.detailKela = this;
		}
		
		private void detach_Siswas(Siswa entity)
		{
			this.SendPropertyChanging();
			entity.detailKela = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HeaderSoal")]
	public partial class HeaderSoal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idSoal;
		
		private System.Nullable<int> _idMapel;
		
		private string _idGuru;
		
		private System.Nullable<int> _idDetailSoal;
		
		private System.Nullable<System.DateTime> _TglDibuat;
		
		private System.Nullable<int> _jmlSoal;
		
		private System.Nullable<int> _idKelas;
		
		private EntitySet<Ujian> _Ujians;
		
		private EntityRef<Guru> _Guru;
		
		private EntityRef<Kelas> _Kelas;
		
		private EntityRef<Mapel> _Mapel;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidSoalChanging(int value);
    partial void OnidSoalChanged();
    partial void OnidMapelChanging(System.Nullable<int> value);
    partial void OnidMapelChanged();
    partial void OnidGuruChanging(string value);
    partial void OnidGuruChanged();
    partial void OnidDetailSoalChanging(System.Nullable<int> value);
    partial void OnidDetailSoalChanged();
    partial void OnTglDibuatChanging(System.Nullable<System.DateTime> value);
    partial void OnTglDibuatChanged();
    partial void OnjmlSoalChanging(System.Nullable<int> value);
    partial void OnjmlSoalChanged();
    partial void OnidKelasChanging(System.Nullable<int> value);
    partial void OnidKelasChanged();
    #endregion
		
		public HeaderSoal()
		{
			this._Ujians = new EntitySet<Ujian>(new Action<Ujian>(this.attach_Ujians), new Action<Ujian>(this.detach_Ujians));
			this._Guru = default(EntityRef<Guru>);
			this._Kelas = default(EntityRef<Kelas>);
			this._Mapel = default(EntityRef<Mapel>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSoal", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idSoal
		{
			get
			{
				return this._idSoal;
			}
			set
			{
				if ((this._idSoal != value))
				{
					this.OnidSoalChanging(value);
					this.SendPropertyChanging();
					this._idSoal = value;
					this.SendPropertyChanged("idSoal");
					this.OnidSoalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMapel", DbType="Int")]
		public System.Nullable<int> idMapel
		{
			get
			{
				return this._idMapel;
			}
			set
			{
				if ((this._idMapel != value))
				{
					if (this._Mapel.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidMapelChanging(value);
					this.SendPropertyChanging();
					this._idMapel = value;
					this.SendPropertyChanged("idMapel");
					this.OnidMapelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idGuru", DbType="VarChar(10)")]
		public string idGuru
		{
			get
			{
				return this._idGuru;
			}
			set
			{
				if ((this._idGuru != value))
				{
					if (this._Guru.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidGuruChanging(value);
					this.SendPropertyChanging();
					this._idGuru = value;
					this.SendPropertyChanged("idGuru");
					this.OnidGuruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDetailSoal", DbType="Int")]
		public System.Nullable<int> idDetailSoal
		{
			get
			{
				return this._idDetailSoal;
			}
			set
			{
				if ((this._idDetailSoal != value))
				{
					this.OnidDetailSoalChanging(value);
					this.SendPropertyChanging();
					this._idDetailSoal = value;
					this.SendPropertyChanged("idDetailSoal");
					this.OnidDetailSoalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TglDibuat", DbType="DateTime")]
		public System.Nullable<System.DateTime> TglDibuat
		{
			get
			{
				return this._TglDibuat;
			}
			set
			{
				if ((this._TglDibuat != value))
				{
					this.OnTglDibuatChanging(value);
					this.SendPropertyChanging();
					this._TglDibuat = value;
					this.SendPropertyChanged("TglDibuat");
					this.OnTglDibuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jmlSoal", DbType="Int")]
		public System.Nullable<int> jmlSoal
		{
			get
			{
				return this._jmlSoal;
			}
			set
			{
				if ((this._jmlSoal != value))
				{
					this.OnjmlSoalChanging(value);
					this.SendPropertyChanging();
					this._jmlSoal = value;
					this.SendPropertyChanged("jmlSoal");
					this.OnjmlSoalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idKelas", DbType="Int")]
		public System.Nullable<int> idKelas
		{
			get
			{
				return this._idKelas;
			}
			set
			{
				if ((this._idKelas != value))
				{
					if (this._Kelas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidKelasChanging(value);
					this.SendPropertyChanging();
					this._idKelas = value;
					this.SendPropertyChanged("idKelas");
					this.OnidKelasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HeaderSoal_Ujian", Storage="_Ujians", ThisKey="idSoal", OtherKey="idSoal")]
		public EntitySet<Ujian> Ujians
		{
			get
			{
				return this._Ujians;
			}
			set
			{
				this._Ujians.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Guru_HeaderSoal", Storage="_Guru", ThisKey="idGuru", OtherKey="idGuru", IsForeignKey=true)]
		public Guru Guru
		{
			get
			{
				return this._Guru.Entity;
			}
			set
			{
				Guru previousValue = this._Guru.Entity;
				if (((previousValue != value) 
							|| (this._Guru.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Guru.Entity = null;
						previousValue.HeaderSoals.Remove(this);
					}
					this._Guru.Entity = value;
					if ((value != null))
					{
						value.HeaderSoals.Add(this);
						this._idGuru = value.idGuru;
					}
					else
					{
						this._idGuru = default(string);
					}
					this.SendPropertyChanged("Guru");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kelas_HeaderSoal", Storage="_Kelas", ThisKey="idKelas", OtherKey="idKelas", IsForeignKey=true)]
		public Kelas Kelas
		{
			get
			{
				return this._Kelas.Entity;
			}
			set
			{
				Kelas previousValue = this._Kelas.Entity;
				if (((previousValue != value) 
							|| (this._Kelas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kelas.Entity = null;
						previousValue.HeaderSoals.Remove(this);
					}
					this._Kelas.Entity = value;
					if ((value != null))
					{
						value.HeaderSoals.Add(this);
						this._idKelas = value.idKelas;
					}
					else
					{
						this._idKelas = default(Nullable<int>);
					}
					this.SendPropertyChanged("Kelas");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mapel_HeaderSoal", Storage="_Mapel", ThisKey="idMapel", OtherKey="idMapel", IsForeignKey=true)]
		public Mapel Mapel
		{
			get
			{
				return this._Mapel.Entity;
			}
			set
			{
				Mapel previousValue = this._Mapel.Entity;
				if (((previousValue != value) 
							|| (this._Mapel.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Mapel.Entity = null;
						previousValue.HeaderSoals.Remove(this);
					}
					this._Mapel.Entity = value;
					if ((value != null))
					{
						value.HeaderSoals.Add(this);
						this._idMapel = value.idMapel;
					}
					else
					{
						this._idMapel = default(Nullable<int>);
					}
					this.SendPropertyChanged("Mapel");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ujians(Ujian entity)
		{
			this.SendPropertyChanging();
			entity.HeaderSoal = this;
		}
		
		private void detach_Ujians(Ujian entity)
		{
			this.SendPropertyChanging();
			entity.HeaderSoal = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DetailSoal")]
	public partial class DetailSoal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _idDetailSoal;
		
		private System.Nullable<int> _idNoSoal;
		
		private System.Nullable<int> _idMapel;
		
		private string _pertanyaan;
		
		private string _jawabanA;
		
		private string _jawabanB;
		
		private string _jawabanC;
		
		private string _jawabanD;
		
		private string _jawabanE;
		
		private System.Nullable<char> _jawabanBenar;
		
		private int _idPrimary;
		
		private EntityRef<Mapel> _Mapel;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDetailSoalChanging(System.Nullable<int> value);
    partial void OnidDetailSoalChanged();
    partial void OnidNoSoalChanging(System.Nullable<int> value);
    partial void OnidNoSoalChanged();
    partial void OnidMapelChanging(System.Nullable<int> value);
    partial void OnidMapelChanged();
    partial void OnpertanyaanChanging(string value);
    partial void OnpertanyaanChanged();
    partial void OnjawabanAChanging(string value);
    partial void OnjawabanAChanged();
    partial void OnjawabanBChanging(string value);
    partial void OnjawabanBChanged();
    partial void OnjawabanCChanging(string value);
    partial void OnjawabanCChanged();
    partial void OnjawabanDChanging(string value);
    partial void OnjawabanDChanged();
    partial void OnjawabanEChanging(string value);
    partial void OnjawabanEChanged();
    partial void OnjawabanBenarChanging(System.Nullable<char> value);
    partial void OnjawabanBenarChanged();
    partial void OnidPrimaryChanging(int value);
    partial void OnidPrimaryChanged();
    #endregion
		
		public DetailSoal()
		{
			this._Mapel = default(EntityRef<Mapel>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDetailSoal", DbType="Int")]
		public System.Nullable<int> idDetailSoal
		{
			get
			{
				return this._idDetailSoal;
			}
			set
			{
				if ((this._idDetailSoal != value))
				{
					this.OnidDetailSoalChanging(value);
					this.SendPropertyChanging();
					this._idDetailSoal = value;
					this.SendPropertyChanged("idDetailSoal");
					this.OnidDetailSoalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idNoSoal", DbType="Int")]
		public System.Nullable<int> idNoSoal
		{
			get
			{
				return this._idNoSoal;
			}
			set
			{
				if ((this._idNoSoal != value))
				{
					this.OnidNoSoalChanging(value);
					this.SendPropertyChanging();
					this._idNoSoal = value;
					this.SendPropertyChanged("idNoSoal");
					this.OnidNoSoalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMapel", DbType="Int")]
		public System.Nullable<int> idMapel
		{
			get
			{
				return this._idMapel;
			}
			set
			{
				if ((this._idMapel != value))
				{
					if (this._Mapel.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidMapelChanging(value);
					this.SendPropertyChanging();
					this._idMapel = value;
					this.SendPropertyChanged("idMapel");
					this.OnidMapelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pertanyaan", DbType="VarChar(MAX)")]
		public string pertanyaan
		{
			get
			{
				return this._pertanyaan;
			}
			set
			{
				if ((this._pertanyaan != value))
				{
					this.OnpertanyaanChanging(value);
					this.SendPropertyChanging();
					this._pertanyaan = value;
					this.SendPropertyChanged("pertanyaan");
					this.OnpertanyaanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jawabanA", DbType="VarChar(MAX)")]
		public string jawabanA
		{
			get
			{
				return this._jawabanA;
			}
			set
			{
				if ((this._jawabanA != value))
				{
					this.OnjawabanAChanging(value);
					this.SendPropertyChanging();
					this._jawabanA = value;
					this.SendPropertyChanged("jawabanA");
					this.OnjawabanAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jawabanB", DbType="VarChar(MAX)")]
		public string jawabanB
		{
			get
			{
				return this._jawabanB;
			}
			set
			{
				if ((this._jawabanB != value))
				{
					this.OnjawabanBChanging(value);
					this.SendPropertyChanging();
					this._jawabanB = value;
					this.SendPropertyChanged("jawabanB");
					this.OnjawabanBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jawabanC", DbType="VarChar(MAX)")]
		public string jawabanC
		{
			get
			{
				return this._jawabanC;
			}
			set
			{
				if ((this._jawabanC != value))
				{
					this.OnjawabanCChanging(value);
					this.SendPropertyChanging();
					this._jawabanC = value;
					this.SendPropertyChanged("jawabanC");
					this.OnjawabanCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jawabanD", DbType="VarChar(MAX)")]
		public string jawabanD
		{
			get
			{
				return this._jawabanD;
			}
			set
			{
				if ((this._jawabanD != value))
				{
					this.OnjawabanDChanging(value);
					this.SendPropertyChanging();
					this._jawabanD = value;
					this.SendPropertyChanged("jawabanD");
					this.OnjawabanDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jawabanE", DbType="VarChar(MAX)")]
		public string jawabanE
		{
			get
			{
				return this._jawabanE;
			}
			set
			{
				if ((this._jawabanE != value))
				{
					this.OnjawabanEChanging(value);
					this.SendPropertyChanging();
					this._jawabanE = value;
					this.SendPropertyChanged("jawabanE");
					this.OnjawabanEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jawabanBenar", DbType="Char(1)")]
		public System.Nullable<char> jawabanBenar
		{
			get
			{
				return this._jawabanBenar;
			}
			set
			{
				if ((this._jawabanBenar != value))
				{
					this.OnjawabanBenarChanging(value);
					this.SendPropertyChanging();
					this._jawabanBenar = value;
					this.SendPropertyChanged("jawabanBenar");
					this.OnjawabanBenarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPrimary", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idPrimary
		{
			get
			{
				return this._idPrimary;
			}
			set
			{
				if ((this._idPrimary != value))
				{
					this.OnidPrimaryChanging(value);
					this.SendPropertyChanging();
					this._idPrimary = value;
					this.SendPropertyChanged("idPrimary");
					this.OnidPrimaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mapel_DetailSoal", Storage="_Mapel", ThisKey="idMapel", OtherKey="idMapel", IsForeignKey=true)]
		public Mapel Mapel
		{
			get
			{
				return this._Mapel.Entity;
			}
			set
			{
				Mapel previousValue = this._Mapel.Entity;
				if (((previousValue != value) 
							|| (this._Mapel.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Mapel.Entity = null;
						previousValue.DetailSoals.Remove(this);
					}
					this._Mapel.Entity = value;
					if ((value != null))
					{
						value.DetailSoals.Add(this);
						this._idMapel = value.idMapel;
					}
					else
					{
						this._idMapel = default(Nullable<int>);
					}
					this.SendPropertyChanged("Mapel");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
